# Generated by Django 3.0.5 on 2021-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('kernel', models.CharField(max_length=100)),
                ('ipaddrs', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('transport', models.CharField(max_length=10)),
                ('protocol', models.CharField(choices=[('tls', 'Transport Layer Security'), ('http', 'Hypertext Transport Protocol'), ('dns', 'Domain Name Service'), ('uc', 'Uncatogoried')], max_length=10)),
                ('conectionbytes', models.IntegerField()),
            ],
        ),
    ]
