# Generated by Django 3.0.5 on 2021-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
