# Generated by Django 3.0.5 on 2021-02-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petal', '0002_auto_20210210_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='kernel',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='host',
            name='name',
        ),
    ]
