# Generated by Django 3.0.5 on 2021-03-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petal', '0003_auto_20210213_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ddosplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thresshold', models.IntegerField()),
                ('ipaddrs', models.CharField(max_length=100)),
                ('service', models.IntegerField()),
            ],
        ),
    ]
